import { z } from 'zod';
import { CATEGORIES, ITEM_STATUSES, JOB_STATUSES, SEASONS } from './enums';

/**
 * Entity shapes returned by the API. Field names are camelCase (the Worker
 * and Better Auth use them as-is). Media columns hold R2 keys; the API adds a
 * presigned URL next to each key when it returns a row, valid for one hour.
 */

const Id = z.uuid();
const Timestamp = z.iso.datetime();
const Key = z.string().min(1);
const SignedUrl = z.url();

// id is z.uuid(): the spec says identifiers are UUIDs generated by the
// Worker. Better Auth's default id generator does not produce UUIDs, so the
// Worker must configure Better Auth to generate UUIDs -- sub-project 2 must
// not skip this.
export const UserSchema = z.object({
  id: Id,
  email: z.email(),
  name: z.string().nullable(),
  image: SignedUrl.nullable(),
  emailVerified: z.boolean(),
  onboardingCompleted: z.boolean(),
  tutorialCompleted: z.boolean(),
  createdAt: Timestamp,
  updatedAt: Timestamp,
});
export type User = z.infer<typeof UserSchema>;

export const AvatarSchema = z.object({
  id: Id,
  userId: Id,
  originalKey: Key,
  originalUrl: SignedUrl,
  modelKey: Key.nullable(),
  modelUrl: SignedUrl.nullable(),
  status: z.enum(JOB_STATUSES),
  error: z.string().nullable(),
  isActive: z.boolean(),
  createdAt: Timestamp,
  updatedAt: Timestamp,
});
export type Avatar = z.infer<typeof AvatarSchema>;

/** Background removal is a job, so an item carries a status like the other two job types. */
export const WardrobeItemSchema = z.object({
  id: Id,
  userId: Id,
  name: z.string().min(1),
  category: z.enum(CATEGORIES),
  imageKey: Key,
  imageUrl: SignedUrl,
  status: z.enum(ITEM_STATUSES),
  error: z.string().nullable(),
  labels: z.array(z.string()),
  colors: z.array(z.string()),
  seasons: z.array(z.enum(SEASONS)),
  isInspiration: z.boolean(),
  createdAt: Timestamp,
  updatedAt: Timestamp,
});
export type WardrobeItem = z.infer<typeof WardrobeItemSchema>;

export const OutfitSchema = z.object({
  id: Id,
  userId: Id,
  name: z.string().nullable(),
  itemIds: z.array(Id),
  thumbnailKey: Key.nullable(),
  thumbnailUrl: SignedUrl.nullable(),
  createdAt: Timestamp,
  updatedAt: Timestamp,
});
export type Outfit = z.infer<typeof OutfitSchema>;

export const GeneratedImageSchema = z.object({
  id: Id,
  userId: Id,
  outfitId: Id.nullable(),
  imageKey: Key.nullable(),
  imageUrl: SignedUrl.nullable(),
  prompt: z.string(),
  status: z.enum(ITEM_STATUSES),
  error: z.string().nullable(),
  createdAt: Timestamp,
});
export type GeneratedImage = z.infer<typeof GeneratedImageSchema>;

/** Every non-2xx response. Codes: validation, unauthorized, not_found, upstream. */
export const ApiErrorSchema = z.object({
  error: z.object({
    code: z.enum(['validation', 'unauthorized', 'not_found', 'upstream']),
    message: z.string(),
  }),
});
export type ApiError = z.infer<typeof ApiErrorSchema>;
